name: Deploy to Sonatype

on:
  push:
    tags:
      - 'v*'

env:
  SIGNING_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
  SIGNING_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: adopt
      - name: Grant gradlew execution permissions
        run: chmod +x gradlew
      - name: Start Gradle
        run: ./gradlew
      - name: Publish all to Sonatype Repository
        run: ./gradlew core:publishAllPublicationsToSonatypeRepository